### PR TITLE
Bump to 40.2

### PR DESCRIPTION
**Pull request by Randomuse1**

### CODE REVIEW

**Comment by Randomuse1** [comment]
Mh, should I use https://gitlab.gnome.org/GNOME/epiphany instead? I wonder..

**Comment by Exalm** [comment]
I don't see a reason to change that tbh.

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by hfiguiere** [comment]
I have seen other failures like this yesterday. Downloading from gnome.org with a 502 error.

@barthalion any idea?

**Comment by barthalion** [comment]
bot, build

**Comment by barthalion** [comment]
@hfiguiere GNOME mirroring service had a hiccup, it's fixed now.

**Comment by hfiguiere** [comment]
thanks!

**Pull request merged**
