### PR TITLE
Remove patch as upstreamed.

### PR DESCRIPTION
**Pull request by Vanadiae**
See https://gitlab.gnome.org/GNOME/epiphany/-/merge_requests/652/diffs

This should be merged if there is a 3.36.2 minor version or when releasing 3.38 (so not now as we're in 3.36.1 at the moment).

### CODE REVIEW

**Comment by Vanadiae** [comment]
the build fail is normal, as a newer version is not out and this PR will need an update on epiphany version number later.

**Comment by bilelmoussaoui** [comment]
> See https://gitlab.gnome.org/GNOME/epiphany/-/merge_requests/652/diffs
> 
> This should be merged if there is a 3.36.2 minor version or when releasing 3.38 (so not now as we're in 3.36.1 at the moment).

I have made that patch upstream, and there was no release since then.

**Comment by bilelmoussaoui** [comment]
> the build fail is normal, as a newer version is not out and this PR will need an update on epiphany version number later.

Any reason for opening it now instead of waiting until there's a release? :)

**Comment by Vanadiae** [comment]
to remind that it needs to be removed, I guess. 🤔️

**Pull request closed without merging**
