### PR TITLE
update to 40

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
cc @exalm

**Comment by Exalm** [comment]
There were a bunch of changes in the repo, do we want them here as well? E.g. elementary stylesheet/icons.

**Comment by bilelmoussaoui** [comment]
> There were a bunch of changes in the repo, do we want them here as well? E.g. elementary stylesheet/icons.

I don't know, maybe? depends on how you want epiphany to behave on elementaryOS. Also 
```
org.gnome.Epiphany.desktop:        AppData problem: tag-invalid : <release> versions are not in order [40.0 before 40.rc]
```
meh :p

**Comment by Exalm** [comment]
GitHub  doesn't let me open a thread on a line not in the diff, so:

```json
        "--talk-name=org.freedesktop.Notifications"
```

* This is gone upstream.
* elementary stylesheet and icons got added.
* libportal got moved below libdazzle

**Comment by Exalm** [comment]
> > There were a bunch of changes in the repo, do we want them here as well? E.g. elementary stylesheet/icons.
> 
> I don't know, maybe? depends on how you want epiphany to behave on elementaryOS. Also
> 
> ```
> org.gnome.Epiphany.desktop:        AppData problem: tag-invalid : <release> versions are not in order [40.0 before 40.rc]
> ```
> 
> meh :p

Oh right, it got fixed after 40.0 already. Use a newer commit than 40.0.

**Comment by Exalm** [comment]
Right now it still hasn't branched, so juts use master.

**Comment by Exalm** [comment]
> I don't know, maybe? depends on how you want epiphany to behave on elementaryOS. Also

I mean, it just works other than the stylesheet, and I think the goal of including them in to repo was specifically to have it here later?

**Comment by mcatanzaro** [comment]
> I don't know about, maybe @mcatanzaro can tell us more about the plans. I thought it was mostly to allow testing the elementary stylesheet easily at development time

@alatiera?

**Comment by alatiera** [comment]
I recall elementary wants to ship ephy as Flatpak in eOS6, for which it wouldbe nice to have the uptodate stylesheet as part of the build and not depend on the gtk extension to be somehow working.

**Comment by mcatanzaro** [comment]
Can the stylesheet be realistically kept up to date if bundled here?

Is there some reliability problem with extensions?

**Comment by Exalm** [comment]
elementary had a plan to keep system stylesheet as Adwaita and only enable elementary ones on per-app basis iirc?

**Comment by alatiera** [comment]
> elementary had a plan to keep Adwita as the system stylesheet and only enable elementary ones on per-app basis iirc?

Well yes, but Ephy is the system browser in Elementary and expected to use the Pantheon mode and elementary stylesheet.

**Comment by Exalm** [comment]
Right, what I mean is extension won't work in that case.

**Comment by bilelmoussaoui** [comment]
I updated the PR, I didn't add the elementary theme though for now.

**Pull request merged**
